"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-not-for-production'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY environment variable is required when DEBUG=False'
        )

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'web',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须尽量靠前
    'django.middleware.security.SecurityMiddleware',
    'web.middleware.request_id.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'web.middleware.rate_limit.RateLimitMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import sys

# 检测是否在 pytest 环境 — 测试用独立 PG 库，不碰开发库
TESTING = any('pytest' in arg for arg in sys.argv)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PG_NAME', 'aifriends'),
        'USER': os.getenv('PG_USER', 'aifriends'),
        'PASSWORD': os.getenv('PG_PASSWORD', ''),
        'HOST': os.getenv('PG_HOST', '127.0.0.1'),
        'PORT': os.getenv('PG_PORT', '5432'),
        'CONN_MAX_AGE': 0 if TESTING else (0 if DEBUG else 300),
        'CONN_HEALTH_CHECKS': True,
        **({
            'TEST': {
                'NAME': f"{os.getenv('PG_NAME', 'aifriends')}_test",
            },
        } if TESTING else {}),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 设置static和media静态文件路径
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic 输出目录

if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / 'static']  # 前端构建产物位置

MEDIA_URL = os.environ.get('MEDIA_URL') or (
    'http://127.0.0.1:8000/media/' if DEBUG else 'https://115.190.245.146/media/'
)
MEDIA_ROOT = BASE_DIR / 'media'


# 使用JWT认证
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# SimpleJWT配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 配置跨域
CORS_ALLOW_CREDENTIALS = True

# CORS 从环境变量读取（逗号分隔），默认兼容本地开发
_cors_env = os.environ.get('DJANGO_CORS_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in _cors_env.split(',') if origin.strip()
] or [
    "http://localhost:5173",
]

# 日志目录
LOG_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'web.middleware.request_id.RequestIdFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} [{request_id}] {module} {process:d} {thread:d}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} [{request_id}] {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['request_id'],
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'web.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'web': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery — Redis broker（异步任务队列）
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')

# 任务完成后才 ack — Worker 崩溃时未完成的任务自动回到队列
CELERY_TASK_ACKS_LATE = True

# Redis URL for rate limiting (uses DB /1, separate from Celery broker /0)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

# Rate Limit Rules — (url_prefix, methods, max_requests, window_seconds)
RATE_LIMIT_RULES = {
    'login':    ('/api/user/account/login/',        ['POST'], 5,  60),
    'register': ('/api/user/account/register/',      ['POST'], 3,  60),
    'chat':     ('/api/friend/message/chat/',        ['POST'], 20, 60),
    'asr':      ('/api/friend/message/asr/asr/',     ['POST'], 10, 60),
    'upload':   ('/api/document/upload/',            ['POST'], 10, 60),
    'default':  ('/api/',                            ['POST', 'PUT', 'PATCH', 'DELETE'], 60, 60),
}

# Paths excluded from rate limiting
RATE_LIMIT_SKIP_PATHS = [
    '/api/health/',
    '/api/user/account/refresh_token/',
    '/static/',
    '/media/',
    '/admin/',
]

# 用户每日 API 配额
QUOTA_LLM_TOKENS_PER_DAY = 100_000
QUOTA_LLM_OVERHEAD_RATIO = 1.8  # 中文 token/char 经验系数（扣除系统 prompt overhead）
QUOTA_TTS_CHARS_PER_DAY = 100_000
QUOTA_ASR_SECONDS_PER_DAY = 3_000
QUOTA_EMBEDDING_TOKENS_PER_DAY = 500_000

# RAG 向量检索配置
RAG_DEFAULT_MAX_RESULTS = 5        # 单次检索默认返回条数（LLM 可通过 max_results 覆盖）
RAG_SIMILARITY_THRESHOLD = 0.5     # 余弦距离阈值（pgvector <=>，0=完全相同 2=语义相反）
RAG_MAX_TOOL_CALLS = 5             # 单次对话最多工具调用次数（防止异常循环）

# APIUsage 原始记录保留天数（超过后自动删除，汇总数据永久保留在 APIUsageDaily）
API_USAGE_RETENTION_DAYS = 90

# 长任务场景，每次只取一个任务避免并发 LLM 调用争抢资源
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 软超时 120s / 硬超时 180s（LLM 调用通常 3-8s）
CELERY_TASK_SOFT_TIME_LIMIT = 120
CELERY_TASK_TIME_LIMIT = 180

# Celery Beat 定时任务调度
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'cleanup-usage-daily': {
        'task': 'web.tasks.cleanup_usage.cleanup_usage_task',
        'schedule': crontab(hour=2, minute=0),
    },
}

# 文件上传大小限制 — 用户文档 RAG（Django 默认 2.5MB 太小）
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
