# Generated by Django 6.0.2 on 2026-04-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chatrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRecord',
            new_name='Message',
        ),
    ]
