# Generated by Django 6.0.2 on 2026-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_chatrecord_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(max_length=50000),
        ),
    ]
