# Generated by Django 6.0.2 on 2026-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='profile',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(help_text='阿里云音色ID', max_length=100),
        ),
    ]
