# Generated by Django 6.0.2 on 2026-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_voice_profile_alter_voice_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
