# Generated by Django 6.0.2 on 2026-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_voice_is_builtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.AddField(
            model_name='character',
            name='introduction',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='system_prompt',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='voice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.JSONField(default=dict, max_length=50000),
        ),
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='title',
            field=models.CharField(choices=[('reply', '回复'), ('memory', '记忆')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user_profile', 'character')},
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['user_profile'], name='web_friend_user_pr_fd288b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['friend', '-created_at'], name='web_message_friend__48b87b_idx'),
        ),
    ]
