# Generated by Django 6.0.2 on 2026-05-19 09:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_character_profile_character_introduction_and_more'),
    ]

    operations = [
        # pgvector 扩展必须在创建 vector 列之前启用
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector'),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
