# Generated by Django 6.0.2 on 2026-05-23 10:02

import django.db.models.deletion
from django.db import migrations, models
from pgvector.django import HnswIndex


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userdocument'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['owner'], name='web_documen_owner_i_aa0ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='web_documen_documen_f9f425_idx'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")
                if schema_editor.connection.vendor == 'postgresql'
                else None
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=HnswIndex(
                fields=['embedding'],
                name='document_chunk_embedding_hnsw_idx',
                opclasses=['vector_cosine_ops'],
            ),
        ),
    ]
