# Generated by Django 6.0.2 on 2026-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_add_userdocument_documentchunk_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_chunk_embedding_hnsw_idx',
        ),
        migrations.AddField(
            model_name='friend',
            name='last_summarized_count',
            field=models.IntegerField(default=0),
        ),
    ]
