# Generated by Django 6.0.2 on 2026-05-31 11:09

from json import loads, JSONDecodeError

from django.db import migrations


def convert_input_to_json(apps, schema_editor):
    """Convert json.dumps strings in Message.input to native JSON lists."""
    Message = apps.get_model('web', 'Message')
    for msg in Message.objects.exclude(input__isnull=True).exclude(input={}):
        if isinstance(msg.input, str):
            try:
                msg.input = loads(msg.input)
                msg.save(update_fields=['input'])
            except (JSONDecodeError, TypeError):
                msg.input = {}
                msg.save(update_fields=['input'])


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_add_last_summarized_count'),
    ]

    operations = [
        migrations.RunPython(convert_input_to_json, reverse_convert),
        # NOTE: RemoveIndex for document_chunk_embedding_hnsw_idx was auto-generated
        # by makemigrations because the model Meta didn't declare the HnswIndex yet.
        # Removed here — the index is recreated in migration 0016.
    ]
