# Generated by Django 6.0.2 on 2026-05-31 11:31

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_fix_message_input_jsonfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='doc_chunk_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
