# Generated by Django 6.0.2 on 2026-06-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_fix_message_input_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('llm', 'LLM 对话/摘要'), ('embedding', '文本向量化'), ('tts', '语音合成'), ('asr', '语音识别')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('token_count', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='调用者（系统知识库处理时可为空）', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='web_apiusag_user_id_3e5d0f_idx'), models.Index(fields=['api_type', '-created_at'], name='web_apiusag_api_typ_7552c2_idx')],
            },
        ),
    ]
