# Generated by Django 6.0.2 on 2026-06-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_add_api_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.userdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='web_retriev_user_id_8e6949_idx'), models.Index(fields=['document'], name='web_retriev_documen_1f70ee_idx')],
            },
        ),
    ]
