# Generated by Django 6.0.2 on 2026-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_retrieval_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for revocation', max_length=255),
        ),
    ]
