# Generated by Django 6.0.2 on 2026-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_add_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of content for incremental update', max_length=64),
        ),
    ]
