# Generated by Django 6.0.2 on 2026-06-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_add_content_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('tts_chars_used', models.IntegerField(default=0)),
                ('asr_seconds_used', models.IntegerField(default=0)),
                ('embedding_tokens_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
