# Generated by Django 6.0.2 on 2026-06-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_add_user_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('api_type', models.CharField(choices=[('llm', 'LLM 对话/摘要'), ('embedding', '文本向量化'), ('tts', '语音合成'), ('asr', '语音识别')], max_length=20)),
                ('total_tokens', models.IntegerField(default=0)),
                ('call_count', models.IntegerField(default=0)),
                ('total_duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='web_apiusag_date_caa050_idx'), models.Index(fields=['user', '-date'], name='web_apiusag_user_id_59e861_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'user', 'api_type'), name='unique_daily_user_api')],
            },
        ),
    ]
