# Generated by Django 6.0.2 on 2026-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_add_api_usage_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, default=list, help_text='RAG 引用来源: [{index,title,chunk_index,content}]'),
        ),
    ]
