# Generated by Django 6.0.2 on 2026-09-16 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_add_message_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(help_text='阿里云音色ID', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9_-]*$', '音色 ID 只能是字母、数字、下划线或连字符')]),
        ),
    ]
