# Generated by Django 6.0.2 on 2026-09-17 12:44

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_public(apps, schema_editor):
    """存量音色置为 public。

    它们此前对所有用户可见（`visibility` 是本次新增、默认 `private`），不迁移就会造成
    可见性回归 —— 线上「观音菩萨」会立刻从所有人的音色选择列表里消失，而它正被一个角色使用。

    只处理 `owner` 为空的行：`owner` 是同一个迁移新增的字段，**应用这一刻所有存量行的 owner
    必然是 NULL**，所以本条与"无条件全表置 public"在当前完全等价；而将来重放该迁移时
    （回滚再前进、或拿含用户音色的库做演练）不会把用户自建的私有音色误置为公开。
    反向操作留 noop：回滚时保留可见性即可，无副作用。
    """
    Voice = apps.get_model('web', 'Voice')
    Voice.objects.filter(owner__isnull=True).update(visibility='public')


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_character_voice_alter_voice_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile'),
        ),
        migrations.AddField(
            model_name='voice',
            name='status',
            field=models.CharField(choices=[('ready', '可用'), ('deploying', '审核中'), ('rejected', '审核未通过')], default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='voice',
            name='visibility',
            field=models.CharField(choices=[('private', '私有'), ('public', '公开')], default='private', max_length=10),
        ),
        migrations.RunPython(mark_existing_public, migrations.RunPython.noop),
    ]
