// 语音输入状态机纯 reducer（LD §6 转移表）。副作用（start/pause/ASR/回填）由 InputField 承担，
// 本模块只做状态流转，便于单测锁定。
export const VOICE_STATES = {
  IDLE: 'idle',
  LISTENING: 'listening',
  TRANSCRIBING: 'transcribing',
  CONFIRM: 'confirm',
  VAD_FAILED: 'vad_failed',
  MIC_DENIED: 'mic_denied',
  ASR_FAILED: 'asr_failed',
}

export const VOICE_EVENTS = {
  CLICK_MIC: 'CLICK_MIC',
  SPEECH_START: 'SPEECH_START',
  SPEECH_END: 'SPEECH_END',
  TRANSCRIPT_TEXT: 'TRANSCRIPT_TEXT',
  TRANSCRIPT_EMPTY: 'TRANSCRIPT_EMPTY',
  ASR_ERROR: 'ASR_ERROR',
  VAD_INIT_FAILED: 'VAD_INIT_FAILED',
  MIC_PERMISSION_DENIED: 'MIC_PERMISSION_DENIED',
  CANCEL: 'CANCEL',
  SEND: 'SEND',
  EDIT_TEXT: 'EDIT_TEXT',
  RETRY: 'RETRY',
}

const TRANSITIONS = {
  [VOICE_STATES.IDLE]: {
    [VOICE_EVENTS.CLICK_MIC]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.SEND]: VOICE_STATES.IDLE,          // 补全行：idle 打字发送
  },
  [VOICE_STATES.LISTENING]: {
    [VOICE_EVENTS.SPEECH_START]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.SPEECH_END]: VOICE_STATES.TRANSCRIBING,
    [VOICE_EVENTS.VAD_INIT_FAILED]: VOICE_STATES.VAD_FAILED,
    [VOICE_EVENTS.MIC_PERMISSION_DENIED]: VOICE_STATES.MIC_DENIED,
    [VOICE_EVENTS.CANCEL]: VOICE_STATES.IDLE,
  },
  [VOICE_STATES.TRANSCRIBING]: {
    [VOICE_EVENTS.TRANSCRIPT_TEXT]: VOICE_STATES.CONFIRM,
    [VOICE_EVENTS.TRANSCRIPT_EMPTY]: VOICE_STATES.ASR_FAILED,
    [VOICE_EVENTS.ASR_ERROR]: VOICE_STATES.ASR_FAILED,
    [VOICE_EVENTS.CANCEL]: VOICE_STATES.IDLE,
  },
  [VOICE_STATES.CONFIRM]: {
    [VOICE_EVENTS.SEND]: VOICE_STATES.IDLE,
    [VOICE_EVENTS.CLICK_MIC]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.EDIT_TEXT]: VOICE_STATES.CONFIRM,
  },
  [VOICE_STATES.VAD_FAILED]: {
    [VOICE_EVENTS.RETRY]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.SEND]: VOICE_STATES.IDLE,          // 补全行：错误态打字发送
  },
  [VOICE_STATES.MIC_DENIED]: {
    [VOICE_EVENTS.RETRY]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.SEND]: VOICE_STATES.IDLE,          // 补全行：错误态打字发送
  },
  [VOICE_STATES.ASR_FAILED]: {
    [VOICE_EVENTS.RETRY]: VOICE_STATES.LISTENING,
    [VOICE_EVENTS.SEND]: VOICE_STATES.IDLE,          // 补全行：错误态打字发送
  },
}

export function voiceReducer(state, event) {
  return TRANSITIONS[state]?.[event] ?? state
}
